<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Pointly POS | Customers</title><?= view('partials/styles') ?></head>
<body><div class="app-shell"><?= view('partials/nav', ['active' => 'customers']) ?><main class="content">
<header class="topbar"><div><p class="eyebrow">Directory</p><h1>Customer accounts</h1><p class="subtitle">Manage and review your current customer records.</p></div><div class="profile"><div class="avatar">AD</div> Admin account</div></header>
<section class="stat-grid"><div class="stat"><div class="stat-icon">♙</div><div><strong><?= count($customers) ?></strong><span>Total customers</span></div></div><div class="stat"><div class="stat-icon">✉</div><div><strong>100%</strong><span>Contact records</span></div></div><div class="stat"><div class="stat-icon">↗</div><div><strong>Active</strong><span>Directory status</span></div></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Customer directory</h2><span><?= count($customers) ?> records found</span></div><a class="button" href="<?= base_url('customers/new') ?>">Add customer +</a></div>
<?php if (session()->getFlashdata('success')): ?><div class="form-error" style="background:#e7faf7;color:#0f9488"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
<?php if (session()->getFlashdata('error')): ?><div class="form-error"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
<div class="table-wrap"><table><thead><tr><th>Customer</th><th>Email address</th><th>Phone number</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php if (!empty($customers)): ?><?php foreach ($customers as $customer): ?><tr><td><div class="person"><span class="person-avatar"><?= esc(strtoupper(substr($customer['full_name'], 0, 1))) ?></span><?= esc($customer['full_name']) ?></div></td><td><?= esc($customer['email']) ?></td><td><?= esc($customer['phone'] ?? '') ?></td><td><span class="badge">Active</span></td><td><a class="action-link" href="<?= base_url('customers/edit/' . $customer['id']) ?>">Edit</a><a class="action-link danger" href="<?= base_url('customers/delete/' . $customer['id']) ?>" onclick="return confirm('Delete this customer?')">Delete</a></td></tr><?php endforeach; ?><?php else: ?><tr><td colspan="5">No customers found.</td></tr><?php endif; ?>
</tbody></table></div></section></main></div></body></html>
